
module.exports = chiste = [
    "Por qué Arnol es rodilla?...\n Porque Silverter Stalon",
    "Conocen el chiste del pedicuro?...\n necesito que me den el pie para contarlo",
    "Les iba a contar el chiste del barco que sale del puerto...\n pero es muy zarpado",
    "Si les cuento el chiste del helado... \n se van a reir una bocha",
    "Les quiero contar el chiste del jardinero... \n cuando podamos",
    "-Hace una semana me hice canibal \n -Y como te va?, \n -bien arranque con el pie derecho",
    "Les iba a contar el chiste de la rosa... \n pero los voy a dejar con la espina.",
    "El otro dia fui a la heladeria con un metro... \n me di todo los gustos",
    "-Hola, con la podologa?... \n Yo tenia turno para hoy, sigue en Pie?",
    "-Sabe inglés?, Use la palabra 'Understand' en una oración. \n -Estoy buscando a mis amigos hacer rato, pero no sé understand",
    "-Seguis vendiendo corpiños?... \n -Si, es mi unico sosten",
    "Te cuento un chiste que me lo mandaron por tweeter?, \n o sea, \n me lo conto un pajarito",
    "-Viste el accidente que tuvo ese señor? Parece que le pegaron con una guitarra, un violín y un bajo... \n - Mmm, todo con cuerda",
    "Si comes dinamita no pasa nada... \n Igual es creer o reventar",
    "-Ayer hice pecho y espalda y hoy piernas y brazos... \n -Estás yendo al gimnasio? \n No, tengo una fabrica de maniquíes",
    "-A qué te dedicás? \n - Arreglo ventiladores de pie. \n - Que, no te sentás nunca?",
    `https://tenor.com/view/oficina-mate-agua-water-hot-gif-15726431 \n Como diría mi amigo que juega ajedrez: "Ja, que mate"`,
    "-Mama en la escuela me dicen revolucionario \n -No es para tanto, Che!",
    `Acá les dejo una pista: \n https://st2.depositphotos.com/1062954/7898/i/600/depositphotos_78986070-stock-photo-race-track-curve-road.jpg`,
    "-Cómo te fue en tu relación con la modista? \n - Y.. tuvimos que ponerle un cierre",
    "Una impresora a la otra: \n -Disculpá, esa hoja es tuya o es impresión mia?",
    "Dos lamparitas: \n - Estás bien? Te veo cansada! \n - Si, estoy fundida",
    "Sabes que animal fue el ultimo en subir al Arca de Noe?.. \n la verdad no é",
    "-Vecino, usted cree que yo o alguien de mi familia sería capaz de robar el Wifi? \n - No, para nada. \n -  Entonces por qué cambió la clave? \n :clown:",
    "-Hola, vengo a patentar la maquina del tiempo. \n - Otra vez?",
    "-Contante un chiste partio, \n -No sesi voy a poder, hay que ver si lo locro",
    "El piloto de un avión al co-piloto\n- Adiviná donde vamos a aterrizar?\n- No sé, dame una pista."
]
